const DEFAULT_ETHEREUM_PROVIDER = 'https://mainnet.gateway.tenderly.co'
const ETHEREUM_PROVIDER = process.env['PROVIDER'] || DEFAULT_ETHEREUM_PROVIDER
const ETHEREUM_RAILGUN_DEPLOYMENT_PROXY = '0xfa7093cdd9ee6932b4eb2c9e1cde7ce00b1fa4b9'

export {
  DEFAULT_ETHEREUM_PROVIDER,
  ETHEREUM_PROVIDER,
  ETHEREUM_RAILGUN_DEPLOYMENT_PROXY
}
